feat: [18] - add update Course status possibility
Cosmopolitan-Inc/elearning-rails-api pull request #104
Opened 2023-09-06 10:51 UTC by tomczak-mateusz

2023-09-06 16:52 UTC, Thevel0per requested changes

2023-09-06 16:52 UTC, Thevel0per commented on app/policies/course_policy.rb
> +  def update_status?
Here we should just check if user is either an admin or an author of the course. We should not check status as it is part of the validation not authorization.

2023-09-06 16:52 UTC, Thevel0per commented on spec/commands/courses/update_status_spec.rb
> +            expect(course.status).to eq('ready')
```suggestion
            expect { result }.to change { course.status }.from('draft').to('ready')
```

Then you can replace all three lines with just this one. Also doing `result rescue nil` here doesn't do anything as you wont get any error thrown.

2023-09-07 11:55 UTC, tomczak-mateusz commented on app/policies/course_policy.rb
> +  def update_status?
fixed for both update endpoints

2023-09-07 11:55 UTC, tomczak-mateusz commented on spec/commands/courses/update_status_spec.rb
> +            expect(course.status).to eq('ready')
fixed

2023-09-07 11:57 UTC, Thevel0per approved these changes

2023-09-07 12:16 UTC, merged